### PR TITLE
Add support for https proxy

### PR DESCRIPTION
**Pull request by GrandPubba**
Related to issue #33 this patch enables proxy support if a proxy URL is specified in the constructor to the Client class.

### CODE REVIEW

**Comment by l12s** [comment]
Have you tested establishing an RTM via the websocket with this?

**Comment by GrandPubba** [comment]
No thanks for pointing that out.  I'll update the pull request when I have the change made and tested.

**Comment by GrandPubba** [comment]
I have added support for configuring the WebSocket to proxy.  I've tested it locally and it is working.

**Comment by GrandPubba** [comment]
Excellent thank you.  How do we go about getting a release to npmjs.org so I can finish the required patch for hubot-slack?

**Pull request merged**
