### PR TITLE
Fix reconnect for websocket closed without breaking pong timeout reconnect

### PR DESCRIPTION
**Pull request by vanm**
This branch aims to support reconnecting if a websocket is terminated / closed cleanly by Slack without disrupting the current "reconnect on Pong timeout" behavior.

Currently, this Client library does not handle the case where a websocket is closed cleanly (Code 1000) by the Server, which is why people have started to call `reconnect` in the `close` event (see #53 and #5).  I have logged many instances of Slack websockets being closed cleanly without errors or pong timeouts.  

Other people noticed this too and started calling reconnect explicitly in this Client's `close` event.  Unfortunately, calling `reconnect` in `close` can result in duplicate websockets being created if it is a part of a Pong Timeout reconnect cycle (See #53).  Because the Pong timeout flow leaves the websocket open, it's `reconnect` calls `close` on an open websocket.  If you were to have a `reconnect` call within the Slack client close event in this case, it would result in two simultaneous `login()` calls.

My hope is that this address some of the issues laid out in #5.  Warning: this will mean anyone calling `reconnect()` in this Client's `close` event needs to re-evaluate their approach.  The "reconnecting" flag should cover them, but I think the library should be entirely responsible for handling `reconnect` based on the `autoReconnect` setting (and not require consumers to handle special cases in `close`).

### CODE REVIEW

**Comment by compulim** [comment]
This is good enough for short term. But I think in the long term, we need to rewrite the connection logic.

To make the connection robust and easy to debug, the connection logic should be driven by a singleton worker (per instance of `Client`). It will be signaled by calling `login`, `connect`, `reconnect`, and `disconnect`.

In additional to existing "ping timeout" scenario, we also need to add timeouts to `rtm.start`, establishing WebSocket connection, and wait for `{"type":"hello"}`.

**Comment by vanm** [comment]
Agreed - this is definitely a short term patch.  I'm not a fan of tracking state as an instance variable between method calls and that wouldn't required if slack.close wasn't tightly bound to ws.close / or we had more expressive flow as you outlined above.

**Comment by ulion** [comment]
There is other issue: each reconnect it sleep longer, I don't think things will go to better in this re-connect way for a long running app.

**Comment by vanm** [comment]
@ulion can you create a new Issue for your concern re: no limit on retries?  Agreed there should be a cap but trying to keep this branch contained to a reconnect patch.

**Comment by ulion** [comment]
well, maybe it's not an issue, I do remember for some case it retry sleep longer each time, but I did checked code it did reset _connAttempts after ws open, so never mind, it's not a big problem.

**Comment by vanm** [comment]
OK, cool.

**Comment by vanm** [comment]
Thoughts @grantmd ?

**Comment by compulim** [comment]
@vanm I am working on a full rewrite of connection logic in https://github.com/compulim/node-slack-client/tree/feat-robust-connection, with the mentioned pattern above. It is still in the work and not fully compatible with current implementation yet.

**Comment by Nesurion** [comment]
@vanm I used your version in our bot for a few days now and it looked promising for a few days, but then we had two open sockets. ie. the bot would react with PONG PONG on a single ping message.
```
2015-08-14 19:52:10.021 +0000 UTC ERROR Last pong is too old: 14.938
2015-08-14 19:52:10.023 +0000 UTC INFO Reconnecting in 1000ms
2015-08-14 19:52:11.023 +0000 UTC INFO Attempting reconnect
2015-08-14 19:52:11.024 +0000 UTC Connecting...
2015-08-14 19:52:11.171 +0000 UTC INFO Slack client closed, waiting for reconnect
2015-08-14 19:52:15.947 +0000 UTC INFO Logged in as *** of ********, but not yet connected
2015-08-14 19:52:27.269 +0000 UTC INFO Slack client now connected
```
I don't see whats gone wrong here, but I hope the logs help. Ping if I can provide you with any more info or logs.

**Comment by vanm** [comment]
@Nesurion Hmm, I don't see duplicate "Slack client now connected" log messages in your output.  The "Slack client closed..." right after Connecting is suspect.  I can step through the code again later this week to see if anything stands out, but if anyone else has ideas, please chime in.

**Comment by Hunchmun** [comment]
Is there any news on this?

**Comment by vanm** [comment]
I haven't seen any suspect duplicate connections.  @Nesurion did you run into any further issues?  I haven't had time to create a test for all of this library's reconnect behavior yet.  My advice is still to run this fork in a test environment and see if it results in an improvement for you.  In my experience this works fine to reconnect and I haven't seen any dups.

**Comment by labeneko** [comment]
:+1:

**Comment by labeneko** [comment]
I tested https://github.com/vanm/node-slack-client/tree/ws-and-team-migration-fixes for defects and it works fine for me.
I can't reproduce the duplicate problem.

**Comment by l12s** [comment]
@vanm - we chatted about the update, so I'll save the full comment, but apologies for the fact we never got to this. The plan is for 2.0.0 to be a better experience for us as maintainers and everyone who's been generous enough with their time to commit too.

**Comment by vanm** [comment]
Thanks @l12s. :+1:

**Pull request closed without merging**
