### PR TITLE
Make Channel#_onFetchHistory work

### PR DESCRIPTION
**Pull request by atmos**
I wanted this in a recent project and @lstoll was kind enough to find what was missing and implement it.

The dev process for running this repo is kinda complicated so a new release would be greatly appreciated. :smiley:

### CODE REVIEW

**Comment by 97-109-107** [comment]
@atmos could you please share an example of how you used this change to read history? Is this just a regular event that can be interpreted with:

````

  this.slack.on('message', function(msg) {
    ...
  });

````

If yes, how do you differentiate between a 'real' message in the room versus a result of fetch history?

**Comment by atmos** [comment]
I'm calling this method after the `login` event is emitted and backfilling the channels that I want.

One drawback is definitely the interaction w/ resetting messages as marked as read. I'm unsure if that's something I need to fix in the client library or if there's a better way to query the API to avoid changing this state.

**Comment by lstoll** [comment]
@97-109-107 we don't differentiate between historical and new messages on events, they're just messages to be handled. Maybe we could set a field on it to indicate that it's historic?

**Comment by atmos** [comment]
I figured out the problem w/ marking messages as unread, we were using the `autoMark` attribute on the client incorrectly.

**Comment by atmos** [comment]
@97-109-107 Here's an example of how I'm using it. https://github.com/atmos/peonies/blob/71cdceecc98af8b8496e4424d3395a38fdc88565/src/main.coffee#L22-L28

**Comment by 97-109-107** [comment]
@lstoll I believe that might be beneficial to other users. In my attemts to solve this for my own use case I tried adding a subtype like so:

````
  _onFetchHistory: (data) =>
    for message in data['messages']
      message['channel'] = @id
      message['subtype'] = 'history'
````

@atmos thanks for the example

**Comment by atmos** [comment]
Are there a lot of places that switch on message subtype? I was trying to avoid having to add another special case and I believe subtype is useful to preserve.

**Comment by brianantonelli** [comment]
+1

**Comment by l12s** [comment]
Ok, first off, I apologize for how long it's taken us to resolve this issue.

I just pushed the 2.0.0 release for this library, which is a ground up refactor with the aim of building a lib that both Slack and our external contributors can easily work with and improve.

That update doesn't include support for what you're describing here yet, but unfortunately deprecates your PR. I've created https://github.com/slackhq/node-slack-client/issues/140 to track the work required to make this happen.

**Pull request closed without merging**
