### PR TITLE
Merge new API calls into master

### PR DESCRIPTION
**Pull request by tjhorner**

### CODE REVIEW

**Comment by evansolomon** [comment]
This PR looks a bit weird.  What commits were you trying to add?

**Comment by tjhorner** [comment]
Mostly cc157c5, but the others look production-ready.

**Comment by evansolomon** [comment]
I think that commit (actually all of these) are already in master.  Right?  Maybe I'm missing something though.

**Comment by tjhorner** [comment]
That's weird... last time I checked, the `updateMessage` method wasn't in master...

**Comment by evansolomon** [comment]
[It's here](https://github.com/slackhq/node-slack-client/blob/master/src/message.coffee#L60-L69)

**Comment by tjhorner** [comment]
Exactly why I closed it

**Comment by tjhorner** [comment]
I'm a bit confused on how to use `updateMessage`. How would I get a `Message` from sending one on `Channel.sendMessage`? It doesn't look like I can.

**Comment by evansolomon** [comment]
`Channel#sendMessage` takes a `Message` object, so I think you'd already have it.

**Comment by tjhorner** [comment]
That leads to my next question:

> How would I get a Message from sending one on `Channel.sendMessage`?

**Comment by tjhorner** [comment]
Sorry, I meant how do I get a timestamp from the server once the message is sent? It's needed for `Message#updateMessage`.

**Comment by evansolomon** [comment]
I'm not sure.  Do you have any example code/error messages/etc?  I haven't personally use this feature, so I don't have much pre-existing knowledge.  What happens if you do something obvious like...

```coffeescript
channel.sendMessage someMessage
someMessage.updateMessage whatever
```

**Comment by tjhorner** [comment]
```javascript
channel.sendMessage("hello");
=> undefined
```

**Comment by evansolomon** [comment]
Are you sure you're supposed to pass strings to channel.sendMessage?

**Pull request closed without merging**
