### PR TITLE
Implement star_added and star_removed

### PR DESCRIPTION
**Pull request by sillygwailo**
Emit the star_added and star_removed events and send along the object of the message that was starred (or had its star removed).

### CODE REVIEW

**Comment by evansolomon** [comment]
Seems fine to me but from [this comment](https://github.com/slackhq/node-slack-client/blob/master/src/client.coffee#L319) it seems like maybe these specially-handled events are not meant to be public API's?  I'm not sure though, maybe one of the Slack guys can weigh in.

**Comment by paulhammond** [comment]
[star_added](https://api.slack.com/events/star_added) and [star_removed](https://api.slack.com/events/star_removed) are both documented, supported parts of our public API!

**Comment by paulhammond** [comment]
Oops, I just hit the merge button by mistake and messed up this pull request. I'm sorry about that!

SO: while star_added and star_removed are both documented events, the code here only handled the case where a message was starred. But, other things can be starred in Slack too - including files, file comments, and channels.

I'd love to merge a pull request that handles star_added or star_removed on any of these objects!

**Comment by paulhammond** [comment]
#27 is the follow up pull request

**Pull request merged**
