### PR TITLE
getChannelByName now strips hashes

### PR DESCRIPTION
**Pull request by yozlet**
Also:
* added first tests
* boosted CS to 1.7.1

This is a fix for https://github.com/slackhq/hubot-slack/issues/136

### CODE REVIEW

**Comment by sukima** [comment]
Any word on this? Seems my scripts have broken also.

For those of us who's script depend on messaging a room there is a workaround that you could use till someone magically merges and releases this (seems that usually takes a long time)?

```coffee
channel = channel.replace /^#/, ""
robot.messageRoom channel, "my message"
```

**Comment by yozlet** [comment]
Pinging @evansolomon & @grantmd - any chance of feedback or merge?

**Comment by evansolomon** [comment]
Oh hi, sorry I never noticed this.  Thanks for adding tests.

Two nitpicks:

1. Since you're upgrade the coffeescript dependency, can you use 1.8.0 (the latest)?
2. The `stubs` variable in the test file isn't use, just kill it.

Other than that it looks good to me.

**Comment by yozlet** [comment]
@evansolomon Sorry for the slow response - done!

**Comment by evansolomon** [comment]
I cleaned up the git history a bit and merged this in 9b454122951c5064624881de302f7f00f816e853

Thanks!

**Pull request closed without merging**
